version: "3.9"
services:
  rook:
    image: "thesummit/rook:latest"
    ports:
      - "8000:8000"
    volumes:
      - "/tmp/postgresql/data:/data"
    environment:
      - ROOK_PORT=8000
      - ROOK_SERVER_SECRET_KEY=some_secret
      - PGDATA=/data/rook
      - POSTGRES_USER=rook_system
      - POSTGRES_USER=rooksystem
